allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  core-js: true
  core-js-pure: true
  msw: true
  protobufjs: true
  sharp: true
  supabase: true
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true
